server:
  port: 8085

spring:
  application:
    name: weather-zuul-server
  zipkin:
    base-url: http://localhost:8087 #链路服务的地址
  sleuth:
    sampler:
      probability: 0.5 #采样比例

eureka:
  client:
    healthcheck:
      enabled: true #开启健康状态
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 10 #eureka client间隔多久去拉取服务注册信息，默认30秒
  instance:
    lease-renewal-interval-in-seconds: 3 #续约间隔心跳时间，默认为30秒，表示eureka-client每隔N秒向eureka-server发送心跳的时间间隔，如果在lease-expiration-duration-in-seconds这个区间内，都没有收到来自client发送的心跳，则server则会将该服务实例注销
    lease-expiration-duration-in-seconds: 5 #续约过期时间，默认为90秒，该值不能设置太长，否则server无法及时感知client的状态
zuul:
  routes:
    city:
      path: /city/**
      service-id: weather-city-server
    data:
      path: /data/**
      service-id: weather-data-server